recipe.cake
=> (GH-36) changed repositoryOwner in cake.recipe

GitReleaseManager.yaml
=> (GH-41) modified the footer in GitReleaseManager.yaml

rider/build.gradle.kts
by adding a workaround for
https://youtrack.jetbrains.com/issue/IDEA-210683
fixes #44
=> (GH-44) fixed the "illegal reflective access operation" warning

.gitignore, README.md
=> (GH-60) added a link to Cake Discussions

.github/workflows/build.yml
=> (GH-94) updated gh actions to current best practices

GitReleaseManager.yaml
=> (GH-95) updated GRM config

recipe.cake
=> (GH-67) updated display-title

rider/src/main/kotlin/net/cakebuild/settings/CakeSettings.kt
=> (GH-104) added expansion of "~" to ${HOME}

rider/src/main/kotlin/net/cakebuild/settings/CakeSettings.kt
=> (GH-112) fixed error in re-hydrating settings

rider/src/test/kotlin/net/cakebuild/settings/CakeSettingsTests.kt
... which should have been there in the first place
and prevented issue #112 before it occurred.
=> (maint) added a simple test for CakeSettings

rider/build.gradle.kts, rider/gradle.properties, rider/gradle/wrapper/gradle-wrapper.properties
https://github.com/JetBrains/intellij-platform-plugin-template/releases/tag/v0.9.0
=> update intellij-platform-plugin-template to v0.9.0

rider/.idea/misc.xml, rider/gradle.properties
=> (GH-108) added RD-2021.1.1 to pluginVerifier

docs/input/docs/integrations/editors/rider/index.cshtml, rider/build.gradle.kts, rider/detekt-config.yml, rider/src/main/kotlin/net/cakebuild/language/codeInsight/TaskInlayHintsProvider.kt, rider/src/main/kotlin/net/cakebuild/language/codeInsight/TaskLineMarkerProvider.kt, rider/src/main/kotlin/net/cakebuild/shared/CakeProject.kt, rider/src/main/resources/META-INF/plugin.xml
to produce the equivalent of Code Lense
Also, added gutter icons for lines containing tasks.
fixes #62
=> (GH-62) added InlayHintsProvider

src/rider/src/main/kotlin/net/cakebuild/actions/CakeTasksTreeAction.kt
=> (GH-118) do not perform actions, if CakeTasksWindow does not exist.

.github/dependabot.yml, src/rider/build.gradle.kts, src/rider/gradle.properties, src/rider/protocol/src/main/kotlin/model/rider/CakePluginModel.kt, src/rider/src/main/kotlin/net/cakebuild/language/codeInsight/TaskInlayHintsProvider.kt, src/rider/src/main/kotlin/net/cakebuild/liveTemplates/CakeContext.kt
=> (#150) removed all warnings from pluginVerifier

src/rider/src/main/resources/liveTemplates/Cake.xml
=> (GH-147) added live templates for #module

.appveyor.yml, .github/workflows/build.yml, build.sh, src/rider/.gitignore, src/rider/.idea/.gitignore, src/rider/.idea/codeStyles/Project.xml, src/rider/.idea/codeStyles/codeStyleConfig.xml, src/rider/.idea/detekt.xml, src/rider/.idea/jarRepositories.xml, src/rider/.idea/libraries-with-intellij-classes.xml, src/rider/.idea/misc.xml, src/rider/build.gradle.kts, src/rider/src/main/java/net/cakebuild/settings/CakeGeneralSettingsEditor.form, src/rider/src/main/java/net/cakebuild/settings/CakeGeneralSettingsEditor.java, src/rider/src/main/kotlin/net/cakebuild/language/CakeFileType.kt, src/rider/src/main/kotlin/net/cakebuild/liveTemplates/CakeContext.kt, src/rider/src/main/kotlin/net/cakebuild/settings/CakeGeneralSettingsConfigurable.kt, src/rider/src/main/kotlin/net/cakebuild/settings/CakeRunnerSettingsConfigurable.kt, src/rider/src/main/kotlin/net/cakebuild/settings/CakeSettings.kt, src/rider/src/main/kotlin/net/cakebuild/shared/CakeProject.kt, src/rider/src/test/kotlin/net/cakebuild/settings/CakeSettingsTests.kt
and enabled using the build-in feature for associating
file patterns with file types.
Fixes #171 
Fixes #160
=> (#171) removed the custom setting for cake extension

docs/input/docs/integrations/editors/rider/index.cshtml, docs/input/docs/integrations/editors/rider/run-configurations.md, docs/input/docs/integrations/editors/rider/templates.md
=> (maint) added missing documentations

src/rider/src/main/kotlin/net/cakebuild/actions/InstallFileToProjectAction.kt
was fixed by wrapping the deletion in runWriteAction
=> (#181) Write access is allowed inside write-action only

src/rider/build.gradle.kts
so templates and the .NET component are
again packed in the plugin
=> (#183) fixed the prepareSandbox task

src/rider/gradle.properties
and added the 2022.1-EAP1 to pluginVerifier
fixes #224
=> (#224) bumped pluginUntilBuild to 221

src/rider/gradle.properties
=> Add support for Rider 2022.2

.github/workflows/build.yml, recipe.cake
and preferredBuildAgentOperatingSystem
=> (maint) changed preferredBuildProviderType

src/rider/.idea/gradle.xml, src/rider/.idea/jarRepositories.xml, src/rider/src/main/kotlin/net/cakebuild/toolwindow/CakeTasksWindowFactory.kt, src/rider/src/main/resources/META-INF/plugin.xml
=> (GH-271) rename ToolWindow

docs/input/docs/integrations/editors/rider/index.cshtml, docs/input/docs/integrations/editors/rider/templates.md
=> (#265) add documentation for the features of Milestone 4.0.0

.github/workflows/build.yml
=> (maint) add .Net 2.1 to CI build

src/rider/gradle.properties
=> (maint) switch platform from 2022.3-snapshot to 2022.3.1

.config/dotnet-tools.json, .github/workflows/build.yml, build.ps1, build.sh, recipe.cake
=> (#352) bump Cake.IntelliJ.Recipe to 0.2.2

recipe.cake, src/dotnet/Directory.Build.props, src/dotnet/cake-rider/CakeFrostingProjectsHost.cs, src/dotnet/cake-rider/TaskMarker/TaskMarkerGutterMark.cs, src/rider/.idea/misc.xml, src/rider/build.gradle.kts, src/rider/gradle.properties, src/rider/settings.gradle.kts, src/rider/src/main/kotlin/net/cakebuild/beforeRunner/EnsureNetToolBeforeRunTaskProvider.kt, src/rider/src/main/kotlin/net/cakebuild/beforeRunner/RestoreNetToolsBeforeRunTaskProvider.kt, src/rider/src/main/kotlin/net/cakebuild/language/codeInsight/TaskInlayHintsProvider.kt, src/rider/src/main/kotlin/net/cakebuild/settings/CakeGeneralSettingsConfigurable.kt, src/rider/src/main/kotlin/net/cakebuild/settings/CakeRunnerSettingsConfigurable.kt, src/rider/src/main/kotlin/net/cakebuild/shared/ui/VerbosityComboBox.kt
=> bump rider platform to 232

src/rider/gradle.properties
=> (#371) bump rider platform to 233

.github/workflows/build.yml, recipe.cake, src/dotnet/Directory.Build.props, src/dotnet/cake-rider/CakeFrostingProjectsHost.cs, src/dotnet/cake-rider/cake-rider.csproj, src/rider/build.gradle.kts, src/rider/gradle.properties
=> (#400) Bump rider platform to 241

src/dotnet/Directory.Build.props, src/dotnet/cake-rider/CakeTaskCollectorStage.cs, src/rider/gradle.properties, src/rider/src/main/kotlin/net/cakebuild/actions/CakeTasksTreeAction.kt
=> (#422) Setting ActionUpdateThread to EDT
